apiVersion: v1
kind: Service
metadata:
  name: php-mysql-app-service
  labels:
    app: php-mysql-app
spec:
  selector:
    app: php-mysql-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80