apiVersion: v1
kind: Service
metadata:
  name: webmaytinh-service
  labels:
    app: webmaytinh
spec:
  selector:
    app: webmaytinh
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
